---
title: "Rendu"
author: Manon Eluard 
format: html
editor: visual
---

```{r Rconfiguration}
#| echo: false 
#| message: false 
library(here)
library(ggplot2)
here::i_am("rendu.Rproj")
dropout <- readRDS("dropout.Rds")
dropout2<-readRDS("top-spotify-hits-2000-2019.Rds")
```

J'ai mis dropout2 qui correspond à spotify (je sais que c'est pas très logique :))

## Exercice 1

```{r}
#| echo: false 
#| message: false 
library(tidyr)
library(dplyr)
```

### Question 1

```{r}
spotify <- dropout2%>% distinct(song, artist, genre)
```

The data set contains `r nrow(spotify)` songs.

### Question 2

```{r}
dropout2 |> 
  group_by(year) |>
  summarise(n()) |>
  knitr::kable()
```

### Question 3

```{r}
nb <- dropout2 |> 
  group_by(artist) |>
  summarise(n_song =n())

nb |> slice_max(n_song) |> pull(artist)
```

### Question 4

```{r}
dropout2 |> 
  group_by(genre) |>
  summarise(min(tempo), max(tempo),mean(tempo),median(tempo), n()) |>
  knitr::kable()
```

### Question 5

```{r}
df <- 
  dropout2|> 
  group_by(year) |> 
  summarise(median(energy),median(danceability))
df
```

### Question 6

```{r}
ggplot(df, aes(x=year, y=`median(energy)`)) + geom_line()
```

```{r}
ggplot(df, aes(x=year, y=`median(danceability)`)) + geom_line()
```

## Exercice 2

### Question 1

```{r}
dropout |>
  group_by(Gender, `Marital status`) |>
  summarise(median(`Age at enrollment`))
```
